version: '3.8'

services:
  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DB_HOST=db
      - DB_TABLE=${DB_TABLE}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}

  db:
    image: mariadb:10.5
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./bookmarx.sql:/docker-entrypoint-initdb.d/db-dump.sql
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}

volumes:
  db_data:
